[package]
name = "aks_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
ecm = "0.4.2"
rand = "0.8.5"
rug = "1.24.1"
